### ISSUE TITLE
debian jessie bash error message

### ISSUE THREAD

**Issue by lvermaak** [KorySchneider/wikit#14]
/usr/local/lib/node_modules/wikit/index.js:4
const path = require('path'),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by KorySchneider** [comment]
What node version are you running?
