### ISSUE TITLE
Crashes when running on macOS

### ISSUE THREAD

**Issue by mbigras** [KorySchneider/wikit#22]
Just installed on macOS on my first search for a `linux` article `wikit` crashes

```
$ sudo npm install wikit -g
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/usr/local/bin/wikit -> /usr/local/lib/node_modules/wikit/index.js
+ wikit@4.0.1
updated 1 package in 3.504s
$ wikit linux
internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at require.page.data (/usr/local/lib/node_modules/wikit/index.js:170:9)
    at /usr/local/lib/node_modules/wikit/node_modules/node-wikipedia/lib/page.js:32:3
    at Request._callback (/usr/local/lib/node_modules/wikit/node_modules/node-wikipedia/lib/dial.js:32:5)
    at Request.self.callback (/usr/local/lib/node_modules/wikit/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/wikit/node_modules/request/request.js:1161:10)
$ npm --version
6.7.0
$ node --version
v11.13.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
```

**Comment by KorySchneider** [comment]
Sorry about that, fixed now!

`npm i -g wikit` to reinstall latest
