### ISSUE TITLE
Wikipedia Wikipedia page results in error

### ISSUE THREAD

**Issue by eitan-j** [KorySchneider/wikit#45]
Searching for the Wikipedia Wikipedia page results in an error:
```
$ wikit wikipedia
⠙ Searching...TypeError: Cannot read property 'substr' of undefined
    at Object.trunc (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/templates/formatting/format.js:50:20)
    at parseTemplate (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/templates/parse.js:35:30)
    at templates.top.forEach.tmpl (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/templates/index.js:35:12)
    at Array.forEach (<anonymous>)
    at Object.parseTemplates [as templates] (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/templates/index.js:34:17)
    at oneSection (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/02-section/index.js:20:16)
    at Object.parseSections [as section] (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/02-section/index.js:72:13)
    at main (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/01-document/index.js:43:25)
    at pages.map.id (/usr/local/lib/node_modules/wikit/node_modules/wtf_wikipedia/src/_fetch/fetch.js:27:14)
    at Array.map (<anonymous>)
wtf_wikipedia error: TypeError: Cannot read property 'substr' of undefined
wikipedia not found :^(
```

I did some testing with old versions, and it seems like this error only occurs in versions 4.1.3 and later.

**Comment by KorySchneider** [comment]
Thanks for reporting. I can't say when I'll have time to look into this, but PRs are welcome!

**Comment by eitan-j** [comment]
This issue doesn't seem to occur anymore. I'm not sure why.
